// Generic async-subtask -> synchronous-future bridge for WASI Preview 3.
//
// wit-bindgen lowers `async func` imports with the component-model subtask ABI:
// calling one returns a `subtask-status` that is either RETURNED (completed
// synchronously) or STARTED with a subtask handle that completes later. This
// module lets synchronous C code drive any number of such calls to completion.
//
// It is deliberately free of any world-specific dependency: it declares the
// canonical component-model async built-ins ("$root" [waitable-*] / [subtask-*])
// itself, so it can be dropped into any project generated by any wit-bindgen
// world. It only needs the C standard library.
//
// Constraints (inherent to the model):
//   - single-threaded reactor use only (no internal locking);
//   - async_block_on / async_block_on_any / async_block_on_all BLOCK on the
//     component-model waitable-set, which is only legal from a *synchronous*
//     lifted export. If your entry export is `async func`, lift it sync (e.g.
//     wit-bindgen `--async=-export:...`) or drive completion with async_dispatch_ready()
//     from your export's callback instead of blocking.

#ifndef ASYNC_FUTURES_H
#define ASYNC_FUTURES_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// Opaque, monotonically-increasing identifier for a registered operation.
typedef uint64_t async_future_t;

// Decode the `subtask-status` returned by a wit-bindgen `[async-lower]` import.
// `status` is the plain uint32 the generated `..._method_*` async call returns.
#define ASYNC_SUBTASK_STATE(status)  ((uint32_t)((status) & 0xf))
#define ASYNC_SUBTASK_HANDLE(status) ((uint32_t)((status) >> 4))
enum {
    ASYNC_SUBTASK_STARTING,
    ASYNC_SUBTASK_STARTED,
    ASYNC_SUBTASK_RETURNED,
    ASYNC_SUBTASK_STARTED_CANCELLED,
    ASYNC_SUBTASK_RETURNED_CANCELLED,
};

// Register a just-started async import.
//
// Call the generated async import with your own result out-param first, then
// pass its returned status here along with a completion callback and userdata:
//
//     struct state { my_result_t result; my_cb_t cb; };
//     struct state* s = malloc(sizeof *s);
//     s->cb = cb;
//     uint32_t status = some_async_import(&args, &s->result);
//     async_future_t f = async_register(status, on_done, s);
//
// `userdata` must be a single heap block; this module takes ownership of it.
// When the subtask completes, `on_done(userdata)` is invoked exactly once (read
// your result out of it there), and the block is freed for you afterwards.
// Returns the future's id.
async_future_t async_register(uint32_t status, void (*on_done)(void* userdata), void* userdata);

// True while `id` has been registered but not yet completed + dispatched.
bool async_future_pending(async_future_t id);

// Fire callbacks for every operation that has already completed, without
// blocking (component-model waitable-set poll). Safe to call anytime.
void async_dispatch_ready(void);

// Block until at least one live operation completes, firing callbacks for all
// that are ready. Returns true if it dispatched at least one; false if there was
// nothing to wait for (no live subtasks) — use that to avoid spinning forever.
bool async_block_on_any(void);

// Block until `id` has completed (and its callback has run).
void async_block_on(async_future_t id);

// Block until every registered operation has completed.
void async_block_on_all(void);

#endif // ASYNC_FUTURES_H
